# Generated by Django 3.0 on 2019-12-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='massage',
            new_name='message',
        ),
    ]
